version: '3.4'

services:
  envoy:
    container_name: EnvoyProxy
    image: envoyproxy/envoy:dev-bd0dc560071d366e4c7ca5a3c7fd8f615f6201d7
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy-config.yml:/etc/envoy/envoy.yaml

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  carservice:
    image: ${DOCKER_REGISTRY-}carservice
    build:
      context: .
      dockerfile: CarService/Dockerfile

  personservice:
    image: ${DOCKER_REGISTRY-}personservice
    build:
      context: .
      dockerfile: PersonService/Dockerfile
